📁 Step 1: Import Libraries & Load Data

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
!pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.11/dist-packages (1.7.4.5)
Requirement already satisfied: bleach in /usr/local/lib/python3.11/dist-packages (from kaggle) (6.2.0)
Requirement already satisfied: certifi>=14.05.14 in /usr/local/lib/python3.11/dist-packages (from kaggle) (2025.4.26)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.11/dist-packages (from kaggle) (3.4.2)
Requirement already satisfied: idna in /usr/local/lib/python3.11/dist-packages (from kaggle) (3.10)
Requirement already satisfied: protobuf in /usr/local/lib/python3.11/dist-packages (from kaggle) (5.29.4)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.11/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.11/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from kaggle) (2.32.3)
Requirement already satisfied: setuptools>=21.0.0 in /usr/local/lib/python3.11/dist-packages (from kaggle) (75.2.0)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.11/dist-packages (from kaggle) (1.17.0)
Requirement already satisfied: text-unidecode in /usr/local/lib/python3.11/dist-packages (from kaggle) (1.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from kaggle) (4.67.1)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.11/dist-packages (from kaggle) (2.4.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.11/dist-packages (from kaggle) (0.5.1)

In [4]:
import os
os.environ['KAGGLE_USERNAME']='asrapervaiz'
os.environ['KAGGLE_KEY'] = '46a2d40a05c1e0f41adf0e11fa8c2ea6'

In [5]:
!kaggle datasets download -d jillanisofttech/pakistan-house-price-dataset

Dataset URL: https://www.kaggle.com/datasets/jillanisofttech/pakistan-house-price-dataset
License(s): other
Downloading pakistan-house-price-dataset.zip to /content
  0% 0.00/7.99M [00:00<?, ?B/s]
100% 7.99M/7.99M [00:00<00:00, 690MB/s]

In [6]:
!unzip /content/pakistan-house-price-dataset.zip

Archive:  /content/pakistan-house-price-dataset.zip
  inflating: zameen-updated.csv

In [25]:
df = pd.read_csv('zameen-updated.csv')

In [26]:
df.head()

,property_id,location_id,page_url,property_type,price,location,city,province_name,latitude,longitude,baths,area,purpose,bedrooms,date_added,agency,agent,Area Type,Area Size,Area Category
0,237062,3325,https://www.zameen.com/Property/g_10_g_10_2_gr...,Flat,10000000,G-10,Islamabad,Islamabad Capital,33.679890,73.012640,2,4 Marla,For Sale,2,02-04-2019,NaN,NaN,Marla,4.0,0-5 Marla
1,346905,3236,https://www.zameen.com/Property/e_11_2_service...,Flat,6900000,E-11,Islamabad,Islamabad Capital,33.700993,72.971492,3,5.6 Marla,For Sale,3,05-04-2019,NaN,NaN,Marla,5.6,5-10 Marla
2,386513,764,https://www.zameen.com/Property/islamabad_g_15...,House,16500000,G-15,Islamabad,Islamabad Capital,33.631486,72.926559,6,8 Marla,For Sale,5,07-17-2019,NaN,NaN,Marla,8.0,5-10 Marla
3,656161,340,https://www.zameen.com/Property/islamabad_bani...,House,43500000,Bani Gala,Islamabad,Islamabad Capital,33.707573,73.151199,4,2 Kanal,For Sale,4,04-05-2019,NaN,NaN,Kanal,2.0,1-5 Kanal
4,841645,3226,https://www.zameen.com/Property/dha_valley_dha...,House,7000000,DHA Defence,Islamabad,Islamabad Capital,33.492591,73.301339,3,8 Marla,For Sale,3,07-10-2019,Easy Property,Muhammad Junaid Ceo Muhammad Shahid Director,Marla,8.0,5-10 Marla

In [27]:
df.describe()

,property_id,location_id,price,latitude,longitude,baths,bedrooms,Area Size
count,1.684460e+05,168446.000000,1.684460e+05,168446.000000,168446.000000,168446.000000,168446.000000,168446.000000
mean,1.559626e+07,4375.936395,1.776576e+07,29.859519,71.239804,2.874227,3.179422,5.892188
std,2.251207e+06,3776.561581,3.531003e+07,3.807870,3.133042,2.463400,1.971401,5.778327
min,8.657500e+04,1.000000,0.000000e+00,11.052446,25.906027,0.000000,0.000000,0.000000
25%,1.488320e+07,1058.000000,1.750000e+05,24.948536,67.130363,0.000000,2.000000,3.000000
50%,1.665851e+07,3286.000000,8.500000e+06,31.459784,73.056182,3.000000,3.000000,5.000000
75%,1.708662e+07,7220.000000,1.950000e+07,33.560887,73.259870,4.000000,4.000000,8.000000
max,1.735772e+07,14220.000000,2.000000e+09,73.184088,80.161430,403.000000,68.000000,800.000000

🔎 Step 2: Initial Data Inspection

In [29]:
df.info()
df.describe(include='all')
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168446 entries, 0 to 168445
Data columns (total 20 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   property_id    168446 non-null  int64
 1   location_id    168446 non-null  int64
 2   page_url       168446 non-null  object
 3   property_type  168446 non-null  object
 4   price          168446 non-null  int64
 5   location       168446 non-null  object
 6   city           168446 non-null  object
 7   province_name  168446 non-null  object
 8   latitude       168446 non-null  float64
 9   longitude      168446 non-null  float64
 10  baths          168446 non-null  int64
 11  area           168446 non-null  object
 12  purpose        168446 non-null  object
 13  bedrooms       168446 non-null  int64
 14  date_added     168446 non-null  object
 15  agency         124375 non-null  object
 16  agent          124374 non-null  object
 17  Area Type      168446 non-null  object
 18  Area Size      168446 non-null  float64
 19  Area Category  168446 non-null  object
dtypes: float64(3), int64(5), object(12)
memory usage: 25.7+ MB

property_id          0
location_id          0
page_url             0
property_type        0
price                0
location             0
city                 0
province_name        0
latitude             0
longitude            0
baths                0
area                 0
purpose              0
bedrooms             0
date_added           0
agency           44071
agent            44072
Area Type            0
Area Size            0
Area Category        0
dtype: int64

🧹 Step 3: Clean Column Names

In [30]:
df.columns = df.columns.str.strip().str.replace(' ', '_').str.lower()

Step 4: Handle Missing Values

In [31]:
df['agency'].fillna('Unknown', inplace=True)
df['agent'].fillna('Unknown', inplace=True)

<ipython-input-31-0ab9ae3fd94c>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['agency'].fillna('Unknown', inplace=True)
<ipython-input-31-0ab9ae3fd94c>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['agent'].fillna('Unknown', inplace=True)

📅 Step 5: Convert Data Types

In [32]:
df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')

In [33]:
df.drop('area', axis=1, inplace=True)

In [34]:
df['property_type'] = df['property_type'].str.title().str.strip()
df['purpose'] = df['purpose'].str.title().str.strip()
df['location'] = df['location'].str.title().str.strip()

In [35]:
df['province_name'] = df['province_name'].replace({
    'Islamabad Capital': 'Islamabad',
    'Sindh ': 'Sindh'  # trailing space fix example
})

🚫 Step 8: Remove Outliers

In [36]:
df = df[df['price'] < 1e8]  # remove unrealistic prices over 100M
df = df[df['area_size'] > 0]  # ensure area is positive

<bound method Series.count of 0         Islamabad
1         Islamabad
2         Islamabad
3         Islamabad
4         Islamabad
            ...
168441        Sindh
168442        Sindh
168443        Sindh
168444        Sindh
168445        Sindh
Name: province_name, Length: 163905, dtype: object>

In [42]:
df.info()
df.isnull().sum()
df.head()

<class 'pandas.core.frame.DataFrame'>
Index: 163905 entries, 0 to 168445
Data columns (total 19 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   property_id    163905 non-null  int64
 1   location_id    163905 non-null  int64
 2   page_url       163905 non-null  object
 3   property_type  163905 non-null  object
 4   price          163905 non-null  int64
 5   location       163905 non-null  object
 6   city           163905 non-null  object
 7   province_name  163905 non-null  object
 8   latitude       163905 non-null  float64
 9   longitude      163905 non-null  float64
 10  baths          163905 non-null  int64
 11  purpose        163905 non-null  object
 12  bedrooms       163905 non-null  int64
 13  date_added     163905 non-null  datetime64[ns]
 14  agency         163905 non-null  object
 15  agent          163905 non-null  object
 16  area_type      163905 non-null  object
 17  area_size      163905 non-null  float64
 18  area_category  163905 non-null  object
dtypes: datetime64[ns](1), float64(3), int64(5), object(10)
memory usage: 25.0+ MB

,property_id,location_id,page_url,property_type,price,location,city,province_name,latitude,longitude,baths,purpose,bedrooms,date_added,agency,agent,area_type,area_size,area_category
0,237062,3325,https://www.zameen.com/Property/g_10_g_10_2_gr...,Flat,10000000,G-10,Islamabad,Islamabad,33.679890,73.012640,2,For Sale,2,2019-02-04,Unknown,Unknown,Marla,4.0,0-5 Marla
1,346905,3236,https://www.zameen.com/Property/e_11_2_service...,Flat,6900000,E-11,Islamabad,Islamabad,33.700993,72.971492,3,For Sale,3,2019-05-04,Unknown,Unknown,Marla,5.6,5-10 Marla
2,386513,764,https://www.zameen.com/Property/islamabad_g_15...,House,16500000,G-15,Islamabad,Islamabad,33.631486,72.926559,6,For Sale,5,2019-07-17,Unknown,Unknown,Marla,8.0,5-10 Marla
3,656161,340,https://www.zameen.com/Property/islamabad_bani...,House,43500000,Bani Gala,Islamabad,Islamabad,33.707573,73.151199,4,For Sale,4,2019-04-05,Unknown,Unknown,Kanal,2.0,1-5 Kanal
4,841645,3226,https://www.zameen.com/Property/dha_valley_dha...,House,7000000,Dha Defence,Islamabad,Islamabad,33.492591,73.301339,3,For Sale,3,2019-07-10,Easy Property,Muhammad Junaid Ceo Muhammad Shahid Director,Marla,8.0,5-10 Marla

💾 Step 9: Save Cleaned Data

In [43]:
df.to_csv('zameen_data_cleaned.csv', index=False)